### PR TITLE
Migration no longer pollutes schema.rb with sequences already assigned t...

### PR DESCRIPTION
**Pull request by HellRok**
Migration no longer pollutes schema.rb with sequences already assigned to tables

Using a slightly modified version of the SQL found at the bottom of
http://wiki.postgresql.org/wiki/Fixing_Sequences we now only put
sequences that aren't assigned to a table and are visible into
schema.rb.

### CODE REVIEW

**Comment by HellRok** [comment]
This fixes issue #1.

**Comment by naw** [comment]
It's possible to have a sequence that is owned by a column that isn't a primary key.

In such a case, I believe those sequences would be incorrectly excluded from schema.rb

**Comment by chrblabla** [comment]
I'd like to see this included. I believe it's a step in the right direction since Rails still doesn't support sequences out of the box. So my :+1: to reactivate this dinosaur and merge it in :)

**Comment by jasonm23** [comment]
👍 please merge this

**Comment by FeeJai** [comment]
Ping?

**Comment by benlinton** [comment]
Before merging this, check out https://github.com/code42/pg_sequencer/pull/11

**Pull request closed without merging**
