### PR TITLE
Support owned_by option and skip dumping primary keys to schema.rb

### PR DESCRIPTION
**Pull request by benlinton**
### Release `1.0.2`

Support `owned_by` option for both `create_sequence` and `change_sequence`.   

Skip dumping to `schema.rb` for sequences that are owned by table primary keys. ActiveRecord is already managing those sequences, and dumping them to `schema.rb` results in a PostgreSQL duplication error.

Bump version to `1.0.2`.  

Resolves issue #1.

### CODE REVIEW

**Comment by tonyc** [comment]
Hi @benlinton, Thanks for the pull request!

I'm no longer involved with Code42, and I haven't touched this project in ages, so I'm not sure exactly who is maintaining this repo anymore, if at all -- @aackerman, any idea?

If you don't get any traction on this PR, you may want to check out the forks to see if there's been progress on those repos - @sportech's fork looks promising as well.

**Comment by aackerman** [comment]
I'm also no longer involved with Code42, you could get in contact with @llhupp, but I would move towards using the fork.

**Comment by benlinton** [comment]
@tonyc @aackerman Thanks for your feedback!  I'll contact @llhupp and look into updating the official gem so it points to a maintained fork.

**Comment by ncreuschling** [comment]
_nudge_

**Pull request closed without merging**
